# =============================================================================
# PREDICTIVE MAINTENANCE — PHASE 4 (MODELING + THRESHOLD TUNING)
# Run     : python phase4_modeling.py
# Requires: X_train.csv, X_test.csv, y_train.csv, y_test.csv, scaler.pkl
#           (generated by phase2_and_3.py)
# Install : pip install scikit-learn joblib matplotlib seaborn
# =============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble     import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics      import (f1_score, precision_score, recall_score,
                                  roc_auc_score, confusion_matrix,
                                  classification_report, roc_curve)

plt.rcParams.update({'figure.facecolor':'#f9f9f9', 'axes.grid':True, 'font.family':'monospace'})

# =============================================================================
# 4.1 — Load Processed Data
# =============================================================================
print("\n" + "="*60)
print("PHASE 4 — MODELING + THRESHOLD TUNING")
print("="*60)

print("\n[4.1] Loading processed data...")
X_train = pd.read_csv('X_train.csv')
X_test  = pd.read_csv('X_test.csv')
y_train = pd.read_csv('y_train.csv').squeeze()
y_test  = pd.read_csv('y_test.csv').squeeze()

print(f"      X_train : {X_train.shape}")
print(f"      X_test  : {X_test.shape}")
print(f"      y_train : Normal={(y_train==0).sum():,}  Failure={(y_train==1).sum():,}")
print(f"      y_test  : Normal={(y_test==0).sum():,}   Failure={(y_test==1).sum():,}")

# =============================================================================
# 4.2 — Define Models
# =============================================================================
print("\n[4.2] Defining models...")

models = {
    'Logistic Regression': LogisticRegression(
        class_weight='balanced', max_iter=1000, random_state=42
    ),
    'Random Forest': RandomForestClassifier(
        n_estimators=200, class_weight='balanced', random_state=42, n_jobs=-1
    ),
    'Gradient Boosting': GradientBoostingClassifier(
        n_estimators=200, learning_rate=0.05, max_depth=4, random_state=42
    ),
}

# =============================================================================
# 4.3 — Train + Evaluate at Default Threshold (0.5)
# =============================================================================
print("\n[4.3] Training all models (default threshold = 0.5)...")
print(f"\n  {'Model':<25} {'F1':>6} {'Prec':>6} {'Rec':>6} {'AUC':>6}")
print("  " + "-"*52)

results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    results[name] = {
        'model' : model,
        'f1'    : f1_score(y_test, y_pred),
        'prec'  : precision_score(y_test, y_pred),
        'rec'   : recall_score(y_test, y_pred),
        'auc'   : roc_auc_score(y_test, y_prob),
        'pred'  : y_pred,
        'prob'  : y_prob,
    }
    r = results[name]
    print(f"  {name:<25} {r['f1']:>6.4f} {r['prec']:>6.4f} {r['rec']:>6.4f} {r['auc']:>6.4f}")

# =============================================================================
# 4.4 — Threshold Tuning on Random Forest
# =============================================================================
# Default threshold = 0.5 → predict failure if probability >= 50%
# We scan every threshold from 0.05 to 0.90 in steps of 0.05
# Pick the one that gives the highest F1 score
# =============================================================================
print("\n[4.4] Threshold tuning on Random Forest...")
print(f"\n  {'Threshold':>10} {'F1':>8} {'Precision':>10} {'Recall':>8}")
print("  " + "-"*40)

rf_prob     = results['Random Forest']['prob']
best_f1     = 0
best_thresh = 0.5
best_pred   = results['Random Forest']['pred']

for t in [x / 100 for x in range(5, 95, 5)]:
    preds = (rf_prob >= t).astype(int)
    f1    = f1_score(y_test, preds)
    prec  = precision_score(y_test, preds, zero_division=0)
    rec   = recall_score(y_test, preds)
    flag  = '  ← new best' if f1 > best_f1 else ''
    if f1 > best_f1:
        best_f1     = f1
        best_thresh = t
        best_pred   = preds
    print(f"  {t:>10.2f} {f1:>8.4f} {prec:>10.4f} {rec:>8.4f}{flag}")

print(f"\n  ✅ Best threshold : {best_thresh}")
print(f"  ✅ Best F1        : {best_f1:.4f}")
print(f"\n  Improvement:")
print(f"    Before tuning → F1: {results['Random Forest']['f1']:.4f}")
print(f"    After  tuning → F1: {best_f1:.4f}  (+{best_f1 - results['Random Forest']['f1']:.4f})")

# =============================================================================
# 4.5 — Final Report with Tuned Threshold
# =============================================================================
print(f"\n[4.5] Classification Report (threshold = {best_thresh})")
print(classification_report(y_test, best_pred, target_names=['Normal','Failure']))

cm = confusion_matrix(y_test, best_pred)
tn, fp, fn, tp = cm.ravel()
print(f"      Confusion Matrix:")
print(f"        True  Negative (correctly predicted normal)   : {tn}")
print(f"        False Positive (predicted failure, was normal) : {fp}")
print(f"        False Negative (missed a real failure)         : {fn}  ← minimize this")
print(f"        True  Positive (correctly caught failure)      : {tp}")

# =============================================================================
# 4.6 — Feature Importance
# =============================================================================
print("\n[4.6] Feature Importance — Random Forest")
rf_model = results['Random Forest']['model']
fi = pd.Series(rf_model.feature_importances_, index=X_train.columns).sort_values(ascending=False)
for feat, imp in fi.items():
    bar = '█' * int(imp * 60)
    print(f"  {feat:<32} {imp:.4f}  {bar}")

# =============================================================================
# 4.7 — Save Charts
# =============================================================================
print("\n[4.7] Saving charts...")

# --- Chart F: Model Comparison ---
fig, axes = plt.subplots(1, 4, figsize=(16, 5))
fig.suptitle('Chart F — Model Comparison (default threshold)', fontweight='bold')
metrics = ['f1','prec','rec','auc']
mlabels = ['F1 Score','Precision','Recall','AUC-ROC']
colors  = ['#1a3a6e','#1a5c2a','#7a5c0a']
mnames  = list(results.keys())
for i, (metric, mlabel) in enumerate(zip(metrics, mlabels)):
    vals = [results[m][metric] for m in mnames]
    bars = axes[i].bar(mnames, vals, color=colors, edgecolor='white')
    for bar, v in zip(bars, vals):
        axes[i].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.005,
                     f'{v:.3f}', ha='center', fontsize=9, fontweight='bold')
    axes[i].set_title(mlabel, fontweight='bold')
    axes[i].set_ylim(0, 1.12)
    axes[i].set_xticklabels(mnames, rotation=15, ha='right', fontsize=8)
plt.tight_layout()
plt.savefig('chartF_model_comparison.png', dpi=130, bbox_inches='tight')
plt.close()
print("  Saved: chartF_model_comparison.png")

# --- Chart G: Threshold Tuning Curve ---
f1_scores, prec_scores, rec_scores = [], [], []
thresholds = [x/100 for x in range(5, 95, 5)]
for t in thresholds:
    preds = (rf_prob >= t).astype(int)
    f1_scores.append(f1_score(y_test, preds))
    prec_scores.append(precision_score(y_test, preds, zero_division=0))
    rec_scores.append(recall_score(y_test, preds))

plt.figure(figsize=(9, 5))
plt.plot(thresholds, f1_scores,   color='#1a3a6e', linewidth=2.5, label='F1 Score')
plt.plot(thresholds, prec_scores, color='#1a5c2a', linewidth=2,   label='Precision', linestyle='--')
plt.plot(thresholds, rec_scores,  color='#8b1a1a', linewidth=2,   label='Recall',    linestyle='--')
plt.axvline(best_thresh, color='orange', linestyle=':', linewidth=2,
            label=f'Best = {best_thresh}')
plt.axvline(0.5, color='grey', linestyle=':', linewidth=1.5, label='Default = 0.5')
plt.xlabel('Decision Threshold')
plt.ylabel('Score')
plt.title('Chart G — Threshold Tuning Curve (Random Forest)', fontweight='bold')
plt.legend(fontsize=9)
plt.tight_layout()
plt.savefig('chartG_threshold_tuning.png', dpi=130, bbox_inches='tight')
plt.close()
print("  Saved: chartG_threshold_tuning.png")

# --- Chart H: Confusion Matrix Before vs After ---
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
fig.suptitle('Chart H — Confusion Matrix: Before vs After Threshold Tuning', fontweight='bold')
for ax, (preds, title) in zip(axes, [
    (results['Random Forest']['pred'], f'Before (threshold=0.50)\nF1={results["Random Forest"]["f1"]:.4f}'),
    (best_pred,                        f'After  (threshold={best_thresh})\nF1={best_f1:.4f}'),
]):
    cm_plot = confusion_matrix(y_test, preds)
    sns.heatmap(cm_plot, annot=True, fmt='d', cmap='Blues', ax=ax, cbar=False,
                xticklabels=['Normal','Failure'], yticklabels=['Normal','Failure'])
    ax.set_title(title, fontsize=10)
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')
plt.tight_layout()
plt.savefig('chartH_confusion_before_after.png', dpi=130, bbox_inches='tight')
plt.close()
print("  Saved: chartH_confusion_before_after.png")

# --- Chart I: ROC Curves ---
plt.figure(figsize=(7, 6))
line_colors = ['#1a3a6e','#1a5c2a','#8b1a1a']
for (name, res), color in zip(results.items(), line_colors):
    fpr, tpr, _ = roc_curve(y_test, res['prob'])
    plt.plot(fpr, tpr, color=color, linewidth=2,
             label=f"{name}  (AUC={res['auc']:.3f})")
plt.plot([0,1],[0,1], 'k--', linewidth=1, label='Random baseline')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Chart I — ROC Curves', fontweight='bold')
plt.legend(fontsize=9)
plt.tight_layout()
plt.savefig('chartI_roc_curves.png', dpi=130, bbox_inches='tight')
plt.close()
print("  Saved: chartI_roc_curves.png")

# --- Chart J: Feature Importance ---
fig, ax = plt.subplots(figsize=(8, 5))
fi_sorted = fi.sort_values()
colors_fi = ['#8b1a1a' if f in ['power','temp_diff','strain'] else '#1a3a6e'
             for f in fi_sorted.index]
fi_sorted.plot(kind='barh', ax=ax, color=colors_fi, edgecolor='white')
ax.set_title('Chart J — Feature Importance (Random Forest)', fontweight='bold')
ax.set_xlabel('Importance Score')
import matplotlib.patches as mpatches
ax.legend(handles=[
    mpatches.Patch(color='#8b1a1a', label='Engineered feature'),
    mpatches.Patch(color='#1a3a6e', label='Raw sensor'),
], fontsize=9)
plt.tight_layout()
plt.savefig('chartJ_feature_importance.png', dpi=130, bbox_inches='tight')
plt.close()
print("  Saved: chartJ_feature_importance.png")

# =============================================================================
# 4.8 — Save Model + Threshold
# =============================================================================
print(f"\n[4.8] Saving model and threshold...")
joblib.dump(rf_model,    'model.pkl')
joblib.dump(best_thresh, 'threshold.pkl')   # API will load this too
print(f"      Saved: model.pkl      (Random Forest)")
print(f"      Saved: threshold.pkl  (best threshold = {best_thresh})")
print(f"      scaler.pkl already saved from Phase 3")

# =============================================================================
# 4.9 — Final Summary
# =============================================================================
print("\n" + "="*60)
print("PHASE 4 SUMMARY")
print("="*60)
print(f"\n  Default threshold results:")
print(f"  {'Model':<25} {'F1':>6} {'Prec':>6} {'Rec':>6} {'AUC':>6}")
print("  " + "-"*52)
for name, res in results.items():
    print(f"  {name:<25} {res['f1']:>6.4f} {res['prec']:>6.4f} {res['rec']:>6.4f} {res['auc']:>6.4f}")

print(f"\n  After threshold tuning (Random Forest @ {best_thresh}):")
print(f"    F1        : {best_f1:.4f}  (was {results['Random Forest']['f1']:.4f})")
print(f"    Precision : {precision_score(y_test, best_pred):.4f}")
print(f"    Recall    : {recall_score(y_test, best_pred):.4f}")
print(f"    AUC       : {results['Random Forest']['auc']:.4f}")

print(f"\n  Saved: model.pkl  threshold.pkl  scaler.pkl")
print(f"  Charts: chartF → chartJ (5 PNG files)")
print(f"\n✅ PHASE 4 COMPLETE — Ready for Phase 5 (API + Deployment)")